### ISSUE TITLE
Feature: search and/or filter

### ISSUE THREAD

**Issue by jgcmarins** [helenapaixao/vagasExplorer#5]
It would be cool to search and/or filter somewhere here:
<img width="1225" alt="Screen Shot 2020-09-25 at 19 53 33" src="https://user-images.githubusercontent.com/5133450/94322416-e6acfe00-ff68-11ea-896a-5380dd809c31.png">

**Comment by helenapaixao** [comment]
great idea, I'll do it  thanks!! :) @jgcmarins

**Comment by helenapaixao** [comment]
hey @jgcmarins the search was implemented!! :)

**Comment by jgcmarins** [comment]
That's awesome!!! Keep the good job \o/
